name: cached_remote_file
description: A simple package to download and cache file from internet
version: 1.0.0+1
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - test/dummy.pdf
